# .github/workflows/firebase-hosting-pull-request.yml
# Workflow para preview de pull requests para la rama main y solo para pull requests de la rama main
name: Deploy to Firebase Hosting (preview)
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - run: npm ci

      - name: Check if secrets are available
        id: check-secrets
        run: |
          if [ -n "${{ secrets.VITE_FIREBASE_API_KEY }}" ]; then
            echo "secrets_available=true" >> $GITHUB_OUTPUT
            echo "Secrets are available"
          else
            echo "secrets_available=false" >> $GITHUB_OUTPUT
            echo "WARNING: Secrets are not available. Skipping build and deploy."
          fi

      - name: Build
        if: steps.check-secrets.outputs.secrets_available == 'true'
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}

      - name: Check dist folder
        if: steps.check-secrets.outputs.secrets_available == 'true'
        run: |
          if [ ! -d "dist" ]; then
            echo "ERROR: dist folder does not exist!"
            echo "Contents of current directory:"
            ls -la
            exit 1
          fi
          echo "dist folder exists. Contents:"
          ls -la dist

      - name: Deploy to preview channel
        if: steps.check-secrets.outputs.secrets_available == 'true'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_M7ABPRO }}
          projectId: m7abpro
          channelId: preview

      - name: Comment on PR
        if: steps.check-secrets.outputs.secrets_available == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Preview deployment skipped: Secrets are not available for this PR. Only PRs from trusted contributors can be deployed to preview.'
            })